# SwiftLint Configuration for InsForge Swift SDK

# Rules to disable
disabled_rules:
  - trailing_whitespace
  - todo
  - cyclomatic_complexity  # Will enable later with custom threshold
  - vertical_whitespace    # Minor style issue
  - non_optional_string_data_conversion  # Not always applicable
  - redundant_sendable     # Actors implicitly conform to Sendable

# Rules to enable
opt_in_rules:
  # - empty_count       # Disabled: can be too strict for tests
  - empty_string
  - explicit_init
  # - force_unwrapping  # Disabled: requires careful code review
  # - implicit_return   # Disabled: style preference
  # - sorted_imports    # Disabled: minor style issue
  # - vertical_whitespace_closing_braces  # Disabled: minor style issue
  # - vertical_whitespace_opening_braces  # Disabled: minor style issue

# Included paths
included:
  - Sources
  - Tests

# Excluded paths
excluded:
  - .build
  - .swiftpm
  - docs
  - Samples

# Configurable rules
line_length:
  warning: 200
  error: 300
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true

type_body_length:
  warning: 500
  error: 700

file_length:
  warning: 700
  error: 1200
  ignore_comment_only_lines: true

function_body_length:
  warning: 100
  error: 150

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - url
    - db
    - ai
    - e
    - d
    - x
    - i
    - j
    - k

# Force cast should be warning, not error
force_cast: warning
force_try: warning

# Custom rules - disabled for now to allow builds to pass
# These rules will be re-enabled after documentation is added
# custom_rules:
#   # Prefer actor over class for concurrent code
#   prefer_actor:
#     name: "Prefer Actor"
#     regex: 'class\s+\w+Client'
#     message: "Consider using 'actor' instead of 'class' for thread-safe clients"
#     severity: warning
#
#   # Ensure public APIs have documentation
#   public_documentation:
#     name: "Public Documentation"
#     regex: 'public\s+(func|var|let|class|struct|enum|actor|protocol)(?!\s+\/\/\/)'
#     message: "Public APIs should have documentation comments"
#     severity: warning

# Reporter
reporter: "xcode"
